# Generated by Django 4.0.1 on 2022-02-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0002_post_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=models.TextField(null=True),
        ),
    ]
