# Generated by Django 4.0.1 on 2022-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_alter_post_opis_alter_post_tekst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
