# Generated by Django 4.0.1 on 2022-03-04 15:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Test'),
        ),
    ]
