# Generated by Django 4.0.1 on 2022-03-06 12:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0005_alter_post_tekst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='opis',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
