# Generated by Django 4.0.1 on 2022-03-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0006_remove_post_opis_post_image_alter_post_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_edytowania',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('niezatwierdzony', 'niezatwierdzony'), ('publiczny', 'publiczny')], default='niezatwierdzony', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posty.post')),
            ],
        ),
    ]
